[package]
name = "hc_zome_agent_registration_storage"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
hdk = "0.0"

hc_zome_agent_registration_storage_consts = { path = "../storage_consts" }

[lib]
crate-type = ["lib"]
